export const Languages = {
  en: {
    id: 0,
    others_language_name: {
      en: 'English',
      vi: 'Viet Nam',
      jp: 'Japanese',
    },
    login_screen: {
      greeting: 'Welcome Back!',
      title: 'Log in',
      email_place_holder: 'Enter Email',
      pass_place_holder: 'Enter Password',
      forgot_pass: 'Forgot Password?',
      new_here: 'New Here? Register',
      mail_error: 'Please fill Email',
      pass_error: 'Please fill Password',
    },
    register_screen: {
      greeting: 'New Here!',
      title: 'Register',
      create: 'Create',
      email_place_holder: 'Enter Email',
      pass_place_holder: 'Enter Password',
      already_have_account: 'Already have an account? Log in',
      mail_error: 'Please fill Email',
      pass_error: 'Please fill Password',
    },
    forgot_password_screen: {
      greeting: 'Opps!',
      title: 'Fogot Password',
      send: 'Send',
      back: 'Back',
      email_place_holder: 'Enter Email',
      mail_error: 'Please fill Email',
    },
    main_screen: {
      header: 'HOME',
      news: 'Trending News',
    },
    home_screen: {
      header: 'HOME',
      tab_name: 'Home',
      news: 'Trending News',
    },
    music_screen: {
      header: 'MUSIC',
      tab_name: 'Music',
      search_place_holder: 'Search Song',
    },
    chat_screen: {
      header: 'CHATS',
      tab_name: 'Chats',
    },
    settings_screen: {
      header: 'SETTINGS',
      tab_name: 'Settings',
      theme: 'Theme Switch',
      theme_content: 'Dark Mode',
      language: 'Language Setting',
      language_content: 'Language',
      about: 'About',
      version: 'Version',
      auth: 'Author',
    },
    profiles_screen: {
      header: 'PROFILES',
      tab_name: 'Profiles',
      name: 'Name',
      email: 'Email',
      uid: 'UID',
      last_login: 'Last Login',
      joined_on: 'Joined On',
      logout: 'Log Out',
      edit: 'Edit',
      update: 'Update Infomation',
    },
  },
  vi: {
    id: 1,
    others_language_name: {
      en: 'Tiếng Anh',
      vi: 'Tiếng Việt',
      jp: 'Tiếng Nhật',
    },
    login_screen: {
      greeting: 'Xin Chào!',
      title: 'Đăng Nhập',
      email_place_holder: 'Nhập Tài Khoản',
      pass_place_holder: 'Nhập Mật Khẩu',
      forgot_pass: 'Quên Mật Khẩu?',
      new_here: 'Chưa Có Tài Khoản? Đăng Ký',
      mail_error: 'Chưa Nhập Tài Khoản',
      pass_error: 'Chưa Nhập Mật Khẩu',
    },
    register_screen: {
      greeting: 'New Here!',
      title: 'Register',
      create: 'Create',
      email_place_holder: 'Enter Email',
      pass_place_holder: 'Enter Password',
      already_have_account: 'Already have an account? Log in',
      mail_error: 'Please fill Email',
      pass_error: 'Please fill Password',
    },
    forgot_password_screen: {
      greeting: 'Opps!',
      title: 'Fogot Password',
      send: 'Send',
      back: 'Back',
      email_place_holder: 'Enter Email',
      mail_error: 'Please fill Email',
    },
    main_screen: {
      header: 'TRANG CHỦ',
      news: 'Tin Tức',
    },
    home_screen: {
      header: 'TRANG CHỦ',
      tab_name: 'Trang Chủ',
      news: 'Tin Tức',
    },
    music_screen: {
      header: 'NHẠC',
      tab_name: 'Nhạc',
      search_place_holder: '曲で検索',
    },
    chat_screen: {
      header: 'TRÒ CHUYỆN',
      tab_name: 'Trò Chuyện',
    },
    settings_screen: {
      header: 'CÀI ĐẶT',
      tab_name: 'Cài Đặt',
      theme: 'Thay Đổi Chủ Đề',
      theme_content: 'Chế Độ Tối',
      language: 'Cài Đặt Ngôn Ngữ',
      language_content: 'Ngôn Ngữ',
      about: 'Thông Tin',
      version: 'Phiên Bản',
      auth: 'Tác Giả',
    },
    profiles_screen: {
      header: 'HỒ SƠ',
      tab_name: 'Hồ Sơ',
      name: 'Tên',
      email: 'Email',
      uid: 'UID',
      last_login: 'Lần Đăng Nhập Cuối',
      joined_on: 'Ngày Tham Gia',
      logout: 'Đăng Xuất',
      edit: 'Đổi Ảnh',
      update: 'Thay Đổi Thông Tin',
    },
  },
  jp: {
    id: 2,
    others_language_name: {
      en: '英語',
      vi: 'ベトナム語',
      jp: '日本語',
    },
    login_screen: {
      greeting: 'ようこそ～',
      title: 'ログイン',
      email_place_holder: 'アカウント',
      pass_place_holder: 'パスワード',
      forgot_pass: 'パスワードが忘れ?',
      new_here: '新規会員登録はこちら',
      mail_error: 'メールを入力してください。',
      pass_error: 'パスワードを入力してください。',
    },
    register_screen: {
      greeting: 'New Here!',
      title: 'Register',
      create: 'Create',
      email_place_holder: 'Enter Email',
      pass_place_holder: 'Enter Password',
      already_have_account: 'Already have an account? Log in',
      mail_error: 'Please fill Email',
      pass_error: 'Please fill Password',
    },
    forgot_password_screen: {
      greeting: 'Opps!',
      title: 'Fogot Password',
      send: 'Send',
      back: 'Back',
      email_place_holder: 'Enter Email',
      mail_error: 'Please fill Email',
    },
    main_screen: {
      header: 'ホームページ',
      news: 'ニュース',
    },
    home_screen: {
      header: 'ホームページ',
      tab_name: 'Home',
      news: 'ニュース',
    },
    music_screen: {
      header: 'ミュージック',
      tab_name: 'Music',
      search_place_holder: '曲で検索',
    },
    chat_screen: {
      header: 'チャット',
      tab_name: 'Chats',
    },
    settings_screen: {
      header: '設定',
      tab_name: 'Settings',
      theme: '外観モード',
      theme_content: 'ダーク',
      language: '言語設定',
      language_content: '言語',
      about: '作者',
      version: 'バージョン',
      auth: '作者',
    },
    profiles_screen: {
      header: 'プロフィール',
      tab_name: 'Profiles',
      name: '名前',
      email: 'メール',
      uid: 'UID',
      last_login: '最終ログイン日',
      joined_on: '参加日',
      logout: 'ログアウト',
      edit: '編集',
      update: '更新',
    },
  },
};
