export const Themes = {
  light: {
    primary: '#f3f4f6',
    secondary: '#fff',
    tertiary: '#4b5563',
    accent: '#0891b2',
    tint: '#111827',
    transparent: 'transparent',
    placeholderTextColor: '#8b9cb5',
    login: '#7DE24E',
    error: 'red',
  },
  dark: {
    primary: '#1f2937',
    secondary: '#111827',
    tertiary: '#d1d5db',
    accent: '#0891b2',
    tint: '#f9fafb',
    transparent: 'transparent',
    placeholderTextColor: '#8b9cb5',
    login: '#7DE24E',
    error: 'red',
  },
  primary: '#f3f4f6',
  secondary: '#fff',
  tertiary: '#4b5563',
  accent: '#0891b2',
  tint: '#111827',
  transparent: 'transparent',
  placeholderTextColor: '#8b9cb5',
  login: '#7DE24E',
  error: 'red',
};
